### ISSUE TITLE
Caching should take into account the given configuration file

### ISSUE THREAD

**Issue by dokempf** [SoilRos/llvm-xray-tools#3]
I have two sequences of configuration files in two subdirectories (the x and y refinement we talked about). Running one will use the cached results from the other because of results caching. It seems caching is done based on filename, not file content.

**Comment by SoilRos** [comment]
Yeah, that's a valid point. I did not consider that case for the cache. Then, no caching is a better default behaviour. I just merged it. Thanks for noticing!
